### ISSUE TITLE
Configurable Gun Skeletons

### ISSUE THREAD

**Issue by pyure** [Shadows-of-Fire/Foundry#43] opened 2019-05-01 18:17 UTC
Hey Shadows,

I'm just gonna add my voice to the list.  Do you mind making these configurable?

**Comment by Shadows-of-Fire** [comment] 2019-05-01 21:38
Duplicate of #42
But I'll see what I can do about it, i suppose.  I was trying not to do anything w/ foundry because I was rewriting the internals, but that looks like its going to take ages.

**Closed as completed by Shadows-of-Fire** 2019-05-01 21:38 UTC

**Comment by pyure** [comment] 2019-05-02 02:34
It wouldn't be the first time you've gone way out of your way to do me a big favour :p 

(Thanks as always)
